# Specify remote theme so github pages can load it from the author's repository
remote_theme: chrisrhymes/bulma-clean-theme
title: Observatory Control System
# Format all site urls consistently
permalink: /:categories/:title/
favicon: /assets/images/favicon.png
defaults:
  -
    scope:
      path: "" # These defaults will apply to all pages
    values:
      hide_footer: true
      show_sidebar: false
      hide_hero: true
      menubar: menu
  -
    scope:
      path: "index.md"
    values:
      hide_hero: false
      hero_image: /assets/images/starry_sky.jpeg
  -
    scope:
      path: "api"
    values:
      menubar: false
